all:
  hosts:
    master:
      ansible_host: IP
    edge:
      ansible_host: IP
    worker1:
      ansible_host: IP
    worker2:
      ansible_host: IP

  vars:
    ansible_user: debian
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
